language: node_js
node_js:
  - "8"
# Cache node_modules
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script: npm install selenium-webdriver
script:
	xvfb-run --server-args="-screen 0 1024x768x24" npm test
