language: node_js
node_js:
  - "8"
# Cache node_modules
cache:
  directories:
    - "node_modules"
install:
  - npm install
script: xvfb-run --server-args="-screen 0 1024x768x24" make test
script:
  # run unit tests
  - npm install selenium-webdriver
  - npm test
