language: node_js
node_js:
  - "8"
# Cache node_modules
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm test
